before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - gcc-5
      - clang-3.9
# Change this to your needs
script: make
