before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
language: c
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
      env: COMPILER=clang-3.9
# Change this to your needs
script: make
